/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EFLURRY_AUTODEFS_H
#define S3EFLURRY_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_FLURRY_NAME "s3eFlurry"
#define S3E_EXT_FLURRY_HASH 0xabad5214

#endif /* !S3EFLURRY_AUTODEFS_H */
